### ISSUE TITLE
Suggestion for menu driven DE addition

### ISSUE THREAD

**Issue by lawmanuk** [Le0xFF/VoidLinuxInstaller#13]
Hi 

Thanks for all your great work.

I just wanted to provide this script I found on the net, which is an amazing addition to your one.

It allowed me to setup a DE of my choice after installing void with your script.

I hope its useful to you, as incorporating into your script will only add benefits after the installation process is complete without forcing the user to choose a DE if they don't want to.

Thanks for the consideration.

[voidupdater.zip](https://github.com/Le0xFF/VoidLinuxInstaller/files/13770113/voidupdater.zip)

**Comment by Le0xFF** [comment]
Hello and thank you for your suggestion!

But as I also said in issue #10, comment (1827387877)[https://github.com/Le0xFF/VoidLinuxInstaller/issues/10#issuecomment-1827387877], the goal of my script is just to help users to install a functional base system without any other addition.
It will be up to every user decide what they want to install, if a DE or not.

**Comment by zen0bit** [comment]
> Hi
> 
> Thanks for all your great work.
> 
> I just wanted to provide this script I found on the net, which is an amazing addition to your one.
> 
> It allowed me to setup a DE of my choice after installing void with your script.
> 
> I hope its useful to you, as incorporating into your script will only add benefits after the installation process is complete without forcing the user to choose a DE if they don't want to.
> 
> Thanks for the consideration.
> 
> [voidupdater.zip](https://github.com/Le0xFF/VoidLinuxInstaller/files/13770113/voidupdater.zip)

Maybe I could merge VoidInuxInstaller into fossraven's void-sh instead...?
https://github.com/oSoWoSo/void-sh
