### ISSUE TITLE
No keyboard on grub

### ISSUE THREAD

**Issue by Astate** [Le0xFF/VoidLinuxInstaller#14]
After installation i dont gave keyboard Working in Grub.
Everything else works fine.
Can you help me to restore grub default keyboard layout?

Thanks

**Comment by Le0xFF** [comment]
Hello, I'm really sorry about the issue!

May I ask which configuration did you choose and which keyboard layout did you pick?
The more information, the better, so I can try to reproduce the issue on my side!

Anyway, to fix the issue, you have to revert to the original grub EFI executable (for reference: [Line 566](https://github.com/Le0xFF/VoidLinuxInstaller/blob/a06770c0d545c6d2056b8fbc8019c328b3163985/vli.sh#L566)):
``` sh
mv /boot/efi/EFI/<BOOTLOADER_ID>/grubx64.efi /boot/efi/EFI/<BOOTLOADER_ID>/BROKEN_grubx64.efi_BROKEN
mv /boot/efi/EFI/<BOOTLOADER_ID>/ORIG_grubx64.efi_ORIG /boot/efi/EFI/<BOOTLOADER_ID>/grubx64.efi
```

and then you should remove the script that it's creating the broken EFI executable (for reference: [Line 559](https://github.com/Le0xFF/VoidLinuxInstaller/blob/a06770c0d545c6d2056b8fbc8019c328b3163985/vli.sh#L559)):
``` sh
rm /etc/kernel.d/post-install/51-grub_ckb
```

It should be working now, but if you want to be sure, probably would be a good idea to reinstall GRUB2!

Please let me know if everything is fine after following this!

**Comment by Astate** [comment]
I have used the script several times with the same problem.
I did a new installation with your script and I still had the same problem.
I needed your fix to resolve the problem, and its grub working fine now

**Comment by Le0xFF** [comment]
I'm glad it's woring fine now i guess issue can be closed now! 😄

But please, as asked, could you please tell me which configuration did bring you to the issue?

* Encryption yes or no?
* LVM yes or no?
* Which keyboard layout did you choose?

This way I can try to reproduce the issue on my side too!

**Comment by Astate** [comment]
Encryption : No
    LVM : No
    Which keyboard layout did you choose : cf
