### ISSUE TITLE
BTRFS Zstd:20

### ISSUE THREAD

**Issue by lawmanuk** [Le0xFF/VoidLinuxInstaller#19]
Could you please consider allowing user to determine how much compression they give to zstd.   I use 20, but do it manually.

Would be helpful for other users to have the option too.

**Comment by Le0xFF** [comment]
As also commented in issue #10, I'm not really interested in allowing users to change the compression level. I think the default value is a good compromise between compression and CPU load.

If user wants, they can do it by modifying the `/etc/fstab` file without a big effort.
