### ISSUE TITLE
Custom void-repositories do not work.

### ISSUE THREAD

**Issue by miusaky** [Le0xFF/VoidLinuxInstaller#4]
Ran the installer on real hardware for the first time and it doesn't seem to be able to handle external void-package repositories. I tried a few forks - including mine - and the script continues to loop with 'please enter a *valid* url'. Even the original void-package repository url returns this. Since there is no method to exit this loop you have to ctrl-c the process and start over. 

Installing without void-repo works fine (EFISTUB at least). I did not attempt the default void-repo option.

**Comment by Le0xFF** [comment]
I pushed commit [fe826aa](https://github.com/Le0xFF/VoidLinuxInstaller/commit/fe826aa85cac7c27a1b1d518be2f345fa22b6354) that should fix this bug!

Before I used a bad way to check if a git repo existed or not and now ~I'm using a probably worse way but~ it should work! :smile:
