### ISSUE TITLE
Installer won't complete

### ISSUE THREAD

**Issue by Arriu** [Le0xFF/VoidLinuxInstaller#6]
Hi,
I'm running the void-live-x86_64-musl-20230628-xfce.iso. After booting, I'm logging out, since it auto signs in with anon account, and logging back in as root. Everything seemingly works fine until the script get to line 2927. I'm getting the following errors, which I have diligently typed over:
```
Mounting folders for chroot...
mount: /mnt/sys: mount point does not exist
	dmesg(1) may have more information after failed mount system call
mount: /mnt/sys: mount point does not exist
	dmesg(1) may have more information after failed mount system call
mount: /mnt/dev: mount point does not exist
	dmesg(1) may have more information after failed mount system call
mount: /mnt/dev: mount point does not exist
	dmesg(1) may have more information after failed mount system call
mount: /mnt/proc: mount point does not exist
	dmesg(1) may have more information after failed mount system call
mount: /mnt/proc: mount point does not exist
	dmesg(1) may have more information after failed mount system call
mount: /mnt/sys/firmware/efi/efivars/: mount point does not exist
	dmesg(1) may have more information after failed mount system call

Copying /etc/resolv.conf...
cp: cannot create regular file '/mnt/etc/': Not a directory

Copying /etc/wpa_supplicant/wpa_supplicant.conf...
cp: cannot create regular file '/mnt/etc/wpa_supplicant/': No such file or directory

Chrooting...

[Press any key to continue...]
cp: cannot create regular file '/mnt/root/': Not a directory
cp: cannot create regular file '/mnt/root/': Not a directory
chroot: failed to run command '/bin/bash': No such file or directory
```

I've checked dmesg but there doesn't seem to be any relevant information in there. Any idea on what could be going wrong?

**Comment by Le0xFF** [comment]
Hello, thank you for reporting this issue and thank you for having diligently typed it here :sweat_smile: !

From what I'm reading from the [docs](https://docs.voidlinux.org/installation/guides/chroot.html#entering-the-chroot), now the `xchroot` tool is directly used to chroot into the Void folder.
This is now the [manual method](https://docs.voidlinux.org/config/containers-and-vms/chroot.html#manual-method), slightly different from what I've implemented in my script.

It shouldn't be a big problem making these changes, but I don't guarantee to be fast.

**Comment by Arriu** [comment]
Thanks for your super quick response. I figured out that adding `mkdir -p /mnt/$dir` between lines 2927 and 2928 resolved the first part of the error. I Looked into your response, and even though iId probably eventually get there, I think it's time that I admit that going through the trouble of doing FDE from a script that I insufficiently understand defeats the point from a security perspective. I'll figure out another way that doesnt' require so much trust. Anyway thanks for your efforts!

**Comment by Le0xFF** [comment]
You can also following [my gist](https://gist.github.com/Le0xFF/ff0e3670c06def675bb6920fe8dd64a3)!
It's not as up to date as the script (missing zswap and uefistub for example) but the script is basically following the same commands of the gist. Maybe it could be a good start!

I will definitely fix this issue, but for sure, the script also needs a good rewrite sooner or later!

**Comment by Le0xFF** [comment]
Hi @Arriu , commit [74ad30e](https://github.com/Le0xFF/VoidLinuxInstaller/commit/74ad30e21227d3a1da6b4fb4387e55c3109c6eed) should fix the issue you were facing. I tried the script with the same iso you were using and everything went fine!

If you're still interested in using my script, as always please use the latest version from the main branch, as stated in the [README](https://github.com/Le0xFF/VoidLinuxInstaller#how-to-run-it)! :smile:

**Comment by Le0xFF** [comment]
Small update on this: the first time I didn't read the iso name really well, I'm sorry.

Only today I realized that you were trying to install the `musl` variant and that part of installation was broken due to the fact that `intel-ucode` is not available in the musl repo, so the installation of the base packages was not completing.

Commit [c1fb1f5](https://github.com/Le0xFF/VoidLinuxInstaller/commit/c1fb1f56acb439cee9898a6cb4a758db90b6208d) should finally fix the issue even for `musl` variant.

And also now the script have been completely rewritten! :smile:

**Comment by Arriu** [comment]
Thank you very much for your efforts.
I'll have a look at the changes in the script and will try to learn from them.
