### ISSUE TITLE
EFIStub with dracut

### ISSUE THREAD

**Issue by Stratos-Crimson** [Le0xFF/VoidLinuxInstaller#7]
Hi,
Why aren't you making efistubs with dracut and then just updating that one stub file. You wouldn't need to update the entry.

**Comment by Le0xFF** [comment]
Hi, thank you for suggestion!

As written in the README, I'm totally not a Linux or script expert, so I learnt a lot of things while making the script itself 😅

Regarding your question, I really have no idea how to create the EFISTUB with dracut and I remember finding some documentation online was really difficult about it.
So if you find any detailed documentation how to do so, please link it here, that would be really helpful!

Or if you feel confident enough, feel free to submit a PR! 😄

**Comment by Stratos-Crimson** [comment]
See #8
